### ISSUE TITLE
Footer hides even if there is no "real scroll"

### ISSUE THREAD

**Issue by qk7b** [bherbst/QuickReturnFooterSample#2]
When there is only one item in the list (or less than the size of the screen in fact)

You scroll, but as there is less items that needed, the list doesn't scroll.

I think the expected behavior is **the footer does not disappear**, but **it does**.

**Comment by maxxx** [comment]
Confirm that

**Comment by bherbst** [comment]
That logic is certainly possible, but outside the scope of this demo. 

You could set up a behavior that asks the RecyclerView's adapter whether there are enough items available to scroll and enable/disable the hiding accordingly.

[`LinearLayoutManager#getLastVisibleItemPosition()`](https://developer.android.com/reference/android/support/v7/widget/LinearLayoutManager.html#findLastVisibleItemPosition()) would be a good place to start.
